<a href="https://colab.research.google.com/github/MWFK/TensorFlow-Certificate-study-materials/blob/main/TF_Dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Libs

In [1]:
import tensorflow as tf

### Tensors

In [38]:
image2 = tf.zeros([2,2,2]) # 2 tables of 2 rows and 2 columns => 2*2 Cube 
image2

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [18]:
image3 = tf.zeros([3,3,3]) # 2 tables of 3 rows and 3 columns => 3*3 Cube 
image3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# expand_dims

In [21]:
# add an outer batch axis by passing axis=0
image1_2 = tf.expand_dims(image2, axis=0) # Table of Table that have 2 rows and 2 columns => 1 batch 2*2 Cube
image1_2
#image1_2.shape.as_list()

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
# add an outer batch axis by passing axis=0
image1_3 = tf.expand_dims(image3, axis=0) #  Table of 3*3 cubes => 1 batch 3*3 Cube 
image1_3

<tf.Tensor: shape=(1, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

# squeeze

In [32]:
# Following standard Python indexing rules, a negative axis counts from the end so axis=-1 adds an inner most dimension
image4 = tf.zeros([10,10,3])
image4 = tf.expand_dims(image, -1)
print(image4.shape.as_list())
'''
Given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed. 
If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying axis.
'''
image4 = tf.squeeze(image4)
image4.shape.as_list()

[10, 10, 3, 1, 1]


[10, 10, 3]

In [33]:
# The new axis location matches Python list.insert(axis, 1)
image5 = tf.zeros([10,10,3])
image5 = tf.expand_dims(image5, axis=1)
print(image5.shape.as_list())
'''
Given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed. 
If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying axis.
'''
image5 = tf.squeeze(image5)
image5.shape.as_list()

[10, 1, 10, 3]


[10, 10, 3]

# Dataset.from_tensor_slices

In [40]:
image2 = tf.zeros([2,2,2])
print(image2)
image2 = tf.data.Dataset.from_tensor_slices(image2)
image2

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32)


<TensorSliceDataset shapes: (2, 2), types: tf.float32>

In [41]:
image2 = tf.zeros([2,2,2])
image2 = tf.expand_dims(image2, axis=-1)
image2 = tf.data.Dataset.from_tensor_slices(image2)
image2

<TensorSliceDataset shapes: (2, 2, 1), types: tf.float32>