<a href="https://colab.research.google.com/github/MWFK/TensorFlow-Certificate-study-materials/blob/main/TF_Dimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Libs

In [27]:
import tensorflow as tf

### Tensors

In [ ]:
image1 = tf.zeros([2,2,2]) # 2 tables of 2 rows and 2 columns => 2*2 Cube 
image1

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
image2 = tf.zeros([3,3,3]) # 3 tables of 3 rows and 3 columns => 3*3 Cube 
image2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

# expand_dims

In [28]:
# add an outer batch axis by passing axis=0
image1_1 = tf.expand_dims(image1, axis=0) # Table of Table that have 2 rows and 2 columns => 1 batch 2*2 Cube
image1_1
#image1_2.shape.as_list()

<tf.Tensor: shape=(1, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# add an outer batch axis by passing axis=-1
image1_2 = tf.expand_dims(image1, axis=-1) 
image1_2
#image1_2.shape.as_list()

<tf.Tensor: shape=(2, 2, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]]]], dtype=float32)>

In [ ]:
# add an outer batch axis by passing axis=0
image1_3 = tf.expand_dims(image2, axis=0) #  Table of 3*3 cubes => 1 batch 3*3 Cube 
image1_3

<tf.Tensor: shape=(1, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

# squeeze

In [ ]:
# Following standard Python indexing rules, a negative axis counts from the end so axis=-1 adds an inner most dimension
image4 = tf.zeros([10,10,3])
image4 = tf.expand_dims(image4, -1)
print(image4.shape.as_list())
'''
Given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed. 
If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying axis.
'''
image4 = tf.squeeze(image4)
image4.shape.as_list()

[10, 10, 3, 1]


[10, 10, 3]

In [ ]:
# The new axis location matches Python list.insert(axis, 1)
image5 = tf.zeros([10,10,3])
image5 = tf.expand_dims(image5, axis=1)
print(image5.shape.as_list())
'''
Given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed. 
If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying axis.
'''
image5 = tf.squeeze(image5)
image5.shape.as_list()

[10, 1, 10, 3]


[10, 10, 3]

# Dataset.from_tensor_slices

In [ ]:
image6 = tf.zeros([2,2,2]) # 2 tables of 2 rows and 2 columns => 2*2 Cube 
print(image6,'\n\n')

image6 = tf.data.Dataset.from_tensor_slices(image6) # Seperate the 2*2cube into 2 different tables of of 2 rows and 2 columns
print(*image6)

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32) 


tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [ ]:
image7 = tf.zeros([2,2,2])
print(image7,'\n\n')

image7 = tf.expand_dims(image7, axis=1)
print(image7,'\n\n')

image7 = tf.data.Dataset.from_tensor_slices(image7)
print(*image7,'\n\n')

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(2, 2, 2), dtype=float32) 


tf.Tensor(
[[[[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]]], shape=(2, 1, 2, 2), dtype=float32) 


tf.Tensor(
[[[0. 0.]
  [0. 0.]]], shape=(1, 2, 2), dtype=float32) tf.Tensor(
[[[0. 0.]
  [0. 0.]]], shape=(1, 2, 2), dtype=float32) 




In [30]:

image = tf.data.Dataset.from_tensor_slices(image1_2)
print(*image,'\n\n')

tf.Tensor(
[[[0.]
  [0.]]

 [[0.]
  [0.]]], shape=(2, 2, 1), dtype=float32) tf.Tensor(
[[[0.]
  [0.]]

 [[0.]
  [0.]]], shape=(2, 2, 1), dtype=float32) 


